version: '3.8'
services:
  fleet_master:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.fleet
    ports:
      - "8000:8000"
    environment:
      - NODE_TYPE=MASTER

  agent_node_0:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.fleet
    environment:
      - NODE_TYPE=WORKER
      - MASTER_URL=http://fleet_master:8000

  agent_node_1:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.fleet
    environment:
      - NODE_TYPE=WORKER
      - MASTER_URL=http://fleet_master:8000
